export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";

export const GET_ALL_GROUP_REQUEST = "GET_ALL_GROUP_REQUEST";
export const GET_ALL_GROUP_SUCCESS = " GET_ALL_GROUP_SUCCESS";
export const GET_ALL_GROUP_FAILD = "GET_ALL_GROUP_FAILD ";

export const CREATE_GROUP_MESSAGE_REQUEST = "GROUP_MESSAGE_REQUEST";
export const CREATE_GROUP_MESSAGE_SUCCESS = "GROUP_MESSAGE_SUCCESS";
export const CREATE_GROUP_MESSAGE_ERROR = "GROUP_MESSAGE_ERROR";

export const GET_All_GROUP_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
export const GET_ALL_GROUP_MESSAGE_SUCCESS = " GET_ALL_GROUP_MESSAGE";
export const GET_ALL_GROUP_MESSAGE_FAILD = "GET_ALL_GROUP_MESSAGE_FAILD ";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCSEE = "ADD_USER_SUCCSEE";
export const ADD_USER_FAILD = "ADD_USER_FAILD ";

export const SEARCH_USER_REQUEST_GROUP = "SEARCH_USER_REQUEST_GROUP";
export const SEARCH_USER_SUCCESS_GROUP = "SEARCH_USER_SUCCESS_GROUP";
export const SEARCH_USER_REQUEST_FAILD = "SEARCH_USER_REQUEST_FAILD ";

export const GET_GROUP_REQUEST = "GET_ALL_GROUP_REQUEST";
export const GET_GROUP_SUCCESS = " GET_ALL_GROUP_SUCCESS";
export const GET_GROUP_FAILD = "GET_ALL_GROUP_FAILD ";
