export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_ERROR = "CREATE_MESSAGE_ERROR";

export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_ERROR = "CREATE_CHAT_ERROR";

export const GET_ALL_CHAT_REQUEST = "ET_ALL_CHAT_REQUEST";
export const GET_ALL_CHAT_SUCCESS = " GET_ALL_CHAT_SUCCESS";
export const GET_ALL_CHAT_FAILD = "GET_ALL_CHAT_FAILD ";

export const GET_ALL_MESSAGE_REQUEST = "GET_ALL_MESSAGE_REQUEST";
export const GET_ALL_MESSAGE_SUCCESS = " GET_ALL_MESSAGE_SUCCESSS";
export const GET_ALL_MESSAGE_FAILD = "GET_ALL_MESSAGE_FAILD ";
